In [ ]:
# Working with Missing Data in Pandas
# Missing Data can occur when no information is provided for one or more
# items or for a whole unit. Missing Data is a very big problem in a real-life scenarios.
# Missing Data can also refer to as NA(Not Available) values in pandas.
# In DataFrame sometimes many datasets simply arrive with missing data,
# either because it exists and was not collected or it never existed.
# For Example, Suppose different users being surveyed may choose not to share their income,
# some users may choose not to share the address in this way many datasets went missing.

# Dataset 1 : https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv

# Dataset 2 : https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

ufo = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
ufo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             18215 non-null  object
 1   Colors Reported  2882 non-null   object
 2   Shape Reported   15597 non-null  object
 3   State            18241 non-null  object
 4   Time             18241 non-null  object
dtypes: object(5)
memory usage: 712.7+ KB

In [ ]:
ufo.isnull().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [ ]:
# remove missing values
# dropna()

# but the concern is, the data with missing values will be delete after hard work of collecting it..huhu
# Use dropna() if dealing with just a few number of missing records

ufo.dropna().shape

(2486, 5)

In [ ]:
# fillna()
# Fill NA/NaN values using the specified method
# fillna() easy to use if using 'object' type data

# inplace=True (make changes permanently on the data)

ufo['City'].fillna(value='CityNotMentioned',inplace=True)

In [ ]:
ufo['Colors Reported'].fillna(value='ColorsNotKnown',inplace=True)
ufo['Shape Reported'].fillna(value='UnknownShape',inplace=True)

In [ ]:
ufo.isnull().sum()

City               0
Colors Reported    0
Shape Reported     0
State              0
Time               0
dtype: int64

In [ ]:
ufo.head(30)

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,ColorsNotKnown,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,ColorsNotKnown,OTHER,NJ,6/30/1930 20:00
2,Holyoke,ColorsNotKnown,OVAL,CO,2/15/1931 14:00
3,Abilene,ColorsNotKnown,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,ColorsNotKnown,LIGHT,NY,4/18/1933 19:00
5,Valley City,ColorsNotKnown,DISK,ND,9/15/1934 15:30
6,Crater Lake,ColorsNotKnown,CIRCLE,CA,6/15/1935 0:00
7,Alma,ColorsNotKnown,DISK,MI,7/15/1936 0:00
8,Eklutna,ColorsNotKnown,CIGAR,AK,10/15/1936 17:00
9,Hubbard,ColorsNotKnown,CYLINDER,OR,6/15/1937 0:00
10,Fontana,ColorsNotKnown,LIGHT,CA,8/15/1937 21:00
11,Waterloo,ColorsNotKnown,FIREBALL,AL,6/1/1939 20:00
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
13,Keokuk,ColorsNotKnown,OVAL,IA,7/7/1939 2:00
14,Ludington,ColorsNotKnown,DISK,MI,6/1/1941 13:00
15,Forest Home,ColorsNotKnown,CIRCLE,CA,7/2/1941 11:30
16,Los Angeles,ColorsNotKnown,UnknownShape,CA,2/25/1942 0:00
17,Hapeville,ColorsNotKnown,UnknownShape,GA,6/1/1942 22:30
18,Oneida,ColorsNotKnown,RECTANGLE,TN,7/15/1942 1:00
19,Bering Sea,RED,OTHER,AK,4/30/1943 23:00
20,Nebraska,ColorsNotKnown,DISK,NE,6/1/1943 15:00
21,CityNotMentioned,ColorsNotKnown,UnknownShape,LA,8/15/1943 0:00
22,CityNotMentioned,ColorsNotKnown,LIGHT,LA,8/15/1943 0:00
23,Owensboro,ColorsNotKnown,RECTANGLE,KY,10/15/1943 11:00
24,Wilderness,ColorsNotKnown,DISK,WV,1/1/1944 10:00
25,San Diego,ColorsNotKnown,CIGAR,CA,1/1/1944 12:00
26,Wilderness,ColorsNotKnown,DISK,WV,1/1/1944 12:00
27,Clovis,ColorsNotKnown,DISK,NM,4/2/1944 11:00
28,Los Alamos,ColorsNotKnown,DISK,NM,6/1/1944 12:00
29,Ft. Duschene,ColorsNotKnown,DISK,UT,6/30/1944 10:00

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          7 non-null      int64
 1   Name        7 non-null      object
 2   Marks       5 non-null      float64
 3   Percentage  3 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 356.0+ bytes

In [ ]:
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
data.isnull().sum()

Id            0
Name          0
Marks         2
Percentage    4
dtype: int64

In [ ]:
data['Marks'].fillna(method='bfill',inplace=True)

In [ ]:
data['Percentage'].fillna(method='ffill',inplace=True)

In [ ]:
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        78.0
2   3  Alex   12.0        67.0
3   4  Alex   12.0        67.0
4   5  Alex   54.0        67.0
5   6  Alex   54.0        67.0
6   7  Alex   65.0        66.0

In [ ]:
# Fill Missing Values By Taking Up A Mean
data = pd.read_csv("https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv")
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
mean_val_marks = data['Marks'].mean()
print(mean_val_marks)

46.4

In [ ]:
mean_val_marks = data['Marks'].mean()
data['Marks'].fillna(value=mean_val_marks,inplace=True)
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex   46.4        67.0
3   4  Alex   12.0         NaN
4   5  Alex   46.4         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
mean_val_per = data['Percentage'].mean()
print(mean_val_per)

70.33333333333333

In [ ]:
mean_val_per = data['Percentage'].mean()
mean_val_per = round(mean_val_per,1)
data['Percentage'].fillna(value=mean_val_per,inplace=True)
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        70.3
2   3  Alex   46.4        67.0
3   4  Alex   12.0        70.3
4   5  Alex   46.4        70.3
5   6  Alex   54.0        70.3
6   7  Alex   65.0        66.0

In [ ]:
# set as 0 for highly sensitive information (account bank balance, ic or passport number)
# after discuss with the client

# use mean for salary, marks and likely same pattern numbers

In [ ]:
# filling missing values using interpolate()
# interpolation method will estimated unknown data point between two known data point
# work only on integer, float data structure

data = pd.read_csv("https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv")
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
data.interpolate()

   Id  Name  Marks  Percentage
0   1  Alex   78.0       78.00
1   2  Alex   23.0       72.50
2   3  Alex   17.5       67.00
3   4  Alex   12.0       66.75
4   5  Alex   33.0       66.50
5   6  Alex   54.0       66.25
6   7  Alex   65.0       66.00

In [ ]:
# Remove Duplicate Records
# Handle Duplicate Data
# Dealing With Duplicate Data

# Create a DataFrame
data = {
      'StudentName': ['Mark', 'Ali', 'Bob', 'John', 'Johny', 'Mark'],
      'Score': [45, 65, 76, 44, 39, 45]
}
df = pd.DataFrame(data)
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45

In [ ]:
# check for duplicate records
print(df.duplicated().sum())

1

In [ ]:
df[df.duplicated()]

  StudentName  Score
5        Mark     45

In [ ]:
df[df['StudentName']=='Mark']

  StudentName  Score
0        Mark     45
5        Mark     45

In [ ]:
# dropping duplicates
df.drop_duplicates(inplace=True)
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
# Create a DataFrame
data = {
      'StudentName': ['Mark', 'Ali', 'Bob', 'John', 'Johny', 'Mark'],
      'Score': [45, 65, 76, 44, 39, 45]
}
df = pd.DataFrame(data)
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45

In [ ]:
# dropping duplicates
df.drop_duplicates(keep='last',inplace=True)
df

  StudentName  Score
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45