In [ ]:
#Pandas Overview Assignment
#Python Analysis Data (Pandas)
# Pandas data science library
import numpy as np
import pandas as pd
print(pd.__version__)

2.2.2

In [ ]:
# numpy array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [ ]:
# pandas series
# A series is 1D labeled array

srs = pd.Series([10,20,30,40])
print(type(srs))
print(srs)
print(srs.shape)



# in numpy, only numbers
# in series, numbers + labels (index)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
dtype: int64
(4,)

In [ ]:
info = pd.Series(['Ali', 29, 9800, 'JB'], index=['name', 'age', 'salary', 'city'])
print(info)
print(info['salary'])
print(info['name'])        # indexing
print(info.get('city'))    # getting data values using get()
# print(info[2]) ==> dia akan bagi warning..so use .iloc instead
print(info.iloc[2])        # iloc --> Index Location

# Series is like a dictionary + array combo

name       Ali
age         29
salary    9800
city        JB
dtype: object
9800
Ali
JB
9800

In [ ]:
# values
print(info.values)

['Ali' 29 9800 'JB']

In [ ]:
# indexing slicing and using loops
s = pd.Series([10,20,30,40,50,60], index=['val1','val2','val3','val4','val5','val6'])
print(s)

# 10  20  30  40  50  60
# 0   1   2   3   4   5
# -6 -5  -4  -3  -2  -1
# v1 v2  v3  v4  v5  v6

# Indexing in Series can be done by using [] or .iloc[] or .loc[]
print('\nIndexing In Series')
print(s.iloc[0])     # for index numbers
print(s.loc['val5'])   # Loc used for Labels
print(s['val2'])       # [] used for labels
print(s.iloc[-1])

val1    10
val2    20
val3    30
val4    40
val5    50
val6    60
dtype: int64

Indexing In Series
10
50
20
60

In [ ]:
# slicing in series
print('\nSlicing In Series')
print(s[1:4])       # 4 will be excluded --> stopIndex
print(s['v1':'v5']) # if perform slicing using Labels, the end Label in included

# 10, 40, 60
print(s[['val1','val4','val6']]) # for specific information s[['','','']]
print(s[['val1','val4','val6']].values) #nk values saja

Slicing In Series
val2    20
val3    30
val4    40
dtype: int64
Series([], dtype: int64)
val1    10
val4    40
val6    60
dtype: int64
[10 40 60]

In [ ]:
# conditional selection
print('\nConditional Selection')
print(s[s%3==0])

Conditional Selection
val3    30
val6    60
dtype: int64

In [ ]:
# using for loop
for i in s:
  print(i)

10
20
30
40
50
60

In [ ]:
for k,v in s.items():
  print(k,v)

val1 10
val2 20
val3 30
val4 40
val5 50
val6 60

In [ ]:
for i in enumerate(s):
  print(i)

(0, 10)
(1, 20)
(2, 30)
(3, 40)
(4, 50)
(5, 60)

In [ ]:
# PandasDataFrame
# It is used to display the information in a tabular fashion (row and column)
# Pandas DataFrame is 2D Array

data = {'name':['John','Alex','Smith'],
        'dept':['IT','HR','Finance'],
        'salary': [3500,4500,5500],
        'city': ['JB','KL','PJ']
        }
print(data)

# ini kalau tunjuk dkt boss yg tktau psl ni, pening kawan tu..so
# DataFrame to the rescue

{'name': ['John', 'Alex', 'Smith'], 'dept': ['IT', 'HR', 'Finance'], 'salary': [3500, 4500, 5500], 'city': ['JB', 'KL', 'PJ']}

In [ ]:
df = pd.DataFrame(data)
print(df)

# see boss pun paham

    name     dept  salary city
0   John       IT    3500   JB
1   Alex       HR    4500   KL
2  Smith  Finance    5500   PJ

In [ ]:
# nak lagi smart, jgn letak print
df = pd.DataFrame(data)
df
# semat wooo

    name     dept  salary city
0   John       IT    3500   JB
1   Alex       HR    4500   KL
2  Smith  Finance    5500   PJ

In [ ]:
data = {
    'Calories': [400,500,600],
    'Duration(min)': [40,50,60]
}

df = pd.DataFrame(data, index=['Day1','Day2','Day3'])
df
# tukar index jadi menarik
# recomended utk data sikit je

      Calories  Duration(min)
Day1       400             40
Day2       500             50
Day3       600             60

In [ ]:
# kalau boss nk data calories je
df['Calories']

Day1    400
Day2    500
Day3    600
Name: Calories, dtype: int64

In [ ]:
print(df['Calories'].values)

[400 500 600]

In [ ]:
# klu boss nk data dari day2
df.loc['Day2']

Calories         500
Duration(min)     50
Name: Day2, dtype: int64

In [ ]:
df.loc[['Day2','Day3']]

      Calories  Duration(min)
Day2       500             50
Day3       600             60