In [ ]:
# Nor Fatin Fatihah Binti Ibrahim
# Using real data to perform Data Cleaning
# Link : https://realpython.com/python-data-cleaning-numpy-pandas/
# Dataset Link : https://raw.githubusercontent.com/realpython/python-data-cleaning/refs/heads/master/Datasets/BL-Flickr-Images-Book.csv

In [ ]:
# import libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# load data
data = pd.read_csv("https://raw.githubusercontent.com/realpython/python-data-cleaning/refs/heads/master/Datasets/BL-Flickr-Images-Book.csv")
data

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8282,4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8283,4158128,NaN,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8284,4159563,NaN,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
8285,4159587,NaN,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8286,4160339,NaN,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [ ]:
# basic info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
 14  Shelfmarks              8287 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 971.3+ KB

In [ ]:
# drop unnecessary columns

to_drop = ['Edition Statement',
            'Corporate Author',
           'Corporate Contributors',
            'Former owner',
            'Engraver',
            'Contributors',
           'Issuance type',
            'Shelfmarks']

data.drop(to_drop, inplace=True, axis=1)

In [ ]:
data.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
data.head(30)

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
5,481,London,1875,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
6,519,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
7,667,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
8,874,London],1676,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,http://www.flickr.com/photos/britishlibrary/ta...
9,1143,London,1679,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
10,1280,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
11,1808,Christiania,1859,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
12,1905,Firenze,1888,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
13,1929,Amsterdam,"1839, 38-54",NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
14,2836,Savona,1897,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...
15,2854,London,1865,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
16,2956,Paris,1860-63,NaN,"Géodésie d'une partie de la Haute Éthiopie,...","ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
17,2957,Paris,1873,NaN,[With eleven maps.],"ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
18,3017,Puerto-Rico,1866,NaN,"[Historia geográfica, civil y politica de la ...","ABBAD Y LASIERRA, Agustín Íñigo - Bishop of...",http://www.flickr.com/photos/britishlibrary/ta...
19,3131,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.",http://www.flickr.com/photos/britishlibrary/ta...
20,4598,Hull,1814,The Author,Peace: a lyric poem. [With prefatory address b...,"ABBOTT, Thomas Eastoe.",http://www.flickr.com/photos/britishlibrary/ta...
21,4884,London,1820,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
22,4976,Oxonii,1800,"J. Cooke, etc.",[Abdollatiphi Historiæ Ægypti compendium. [Wit...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
23,5382,London,"1847, 48 [1846-48]",Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
24,5385,London,[1897?],"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
25,5389,London,[1897?],"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
26,5432,Milano,1893,NaN,Signa: opera in tre atti [founded on the novel...,"A'BECKETT, Gilbert Arthur - and RUDALL (H. A.)",http://www.flickr.com/photos/britishlibrary/ta...
27,6036,London,1805,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",NaN,http://www.flickr.com/photos/britishlibrary/ta...
28,6821,Aberdeen,1837,J. Davidson & Co.,Description of the Coast between Aberdeen and ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
29,7521,Wien,1896,NaN,Aus Kaukasischen Ländern. Reisebriefe von H. ...,"ABICH, Wilhelm Hermann.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
# check for missing values
data.isnull().sum()

Identifier                 0
Place of Publication       0
Date of Publication      181
Publisher               4195
Title                      0
Author                  1778
Flickr URL                 0
dtype: int64

In [ ]:
# fill the missing values

data['Author'].fillna(value='UnknownAuthor',inplace=True)
data['Publisher'].fillna(value='PublisherNotKnown',inplace=True)

In [ ]:
data.head(30)

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
5,481,London,1875,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
6,519,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
7,667,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,PublisherNotKnown,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
8,874,London],1676,PublisherNotKnown,"A Warning to the inhabitants of England, and L...",Remaʿ.,http://www.flickr.com/photos/britishlibrary/ta...
9,1143,London,1679,PublisherNotKnown,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
10,1280,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
11,1808,Christiania,1859,PublisherNotKnown,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
12,1905,Firenze,1888,PublisherNotKnown,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
13,1929,Amsterdam,"1839, 38-54",PublisherNotKnown,De Aardbol. Magazijn van hedendaagsche land- e...,UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
14,2836,Savona,1897,PublisherNotKnown,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...
15,2854,London,1865,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
16,2956,Paris,1860-63,PublisherNotKnown,"Géodésie d'une partie de la Haute Éthiopie,...","ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
17,2957,Paris,1873,PublisherNotKnown,[With eleven maps.],"ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
18,3017,Puerto-Rico,1866,PublisherNotKnown,"[Historia geográfica, civil y politica de la ...","ABBAD Y LASIERRA, Agustín Íñigo - Bishop of...",http://www.flickr.com/photos/britishlibrary/ta...
19,3131,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.",http://www.flickr.com/photos/britishlibrary/ta...
20,4598,Hull,1814,The Author,Peace: a lyric poem. [With prefatory address b...,"ABBOTT, Thomas Eastoe.",http://www.flickr.com/photos/britishlibrary/ta...
21,4884,London,1820,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
22,4976,Oxonii,1800,"J. Cooke, etc.",[Abdollatiphi Historiæ Ægypti compendium. [Wit...,UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
23,5382,London,"1847, 48 [1846-48]",Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
24,5385,London,[1897?],"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
25,5389,London,[1897?],"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
26,5432,Milano,1893,PublisherNotKnown,Signa: opera in tre atti [founded on the novel...,"A'BECKETT, Gilbert Arthur - and RUDALL (H. A.)",http://www.flickr.com/photos/britishlibrary/ta...
27,6036,London,1805,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
28,6821,Aberdeen,1837,J. Davidson & Co.,Description of the Coast between Aberdeen and ...,UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
29,7521,Wien,1896,PublisherNotKnown,Aus Kaukasischen Ländern. Reisebriefe von H. ...,"ABICH, Wilhelm Hermann.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
data.loc[206]

Identifier                                                          77554
Place of Publication                                               London
Date of Publication                                                  1848
Publisher                                                 Richard Bentley
Title                   Rambles in the romantic regions of the Hartz M...
Author                                   Andersen, H. C. (Hans Christian)
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [ ]:
# remove spaces and lowercase all column names
data.columns = data.columns.str.strip().str.lower()
data.columns

Index(['identifier', 'place of publication', 'date of publication',
       'publisher', 'title', 'author', 'flickr url'],
      dtype='object')

In [ ]:
# extract only 4-digit year using regex
data['date of publication'] = data['date of publication'].str.extract(r'(\d{4})', expand=False)

# Convert to numeric
data['date of publication'] = pd.to_numeric(data['date of publication'], errors='coerce')

In [ ]:
# fix invalid year values
data = data[(data['date of publication'] >= 1000) | (data['date of publication'].isnull())]

In [ ]:
# Fill Missing Values (Date of Publication) By using mean

mean_val_marks = data['date of publication'].mean()
data['date of publication'].fillna(value=mean_val_marks,inplace=True)
data.head(30)

,identifier,place of publication,date of publication,publisher,title,author,flickr url
0,206,London,1879.000000,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868.000000,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869.000000,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851.000000,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857.000000,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
5,481,London,1875.000000,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
6,519,London,1872.000000,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
7,667,"pp. 40. G. Bryan & Co: Oxford, 1898",1857.813425,PublisherNotKnown,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
8,874,London],1676.000000,PublisherNotKnown,"A Warning to the inhabitants of England, and L...",Remaʿ.,http://www.flickr.com/photos/britishlibrary/ta...
9,1143,London,1679.000000,PublisherNotKnown,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
10,1280,Coventry,1802.000000,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
11,1808,Christiania,1859.000000,PublisherNotKnown,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
12,1905,Firenze,1888.000000,PublisherNotKnown,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
13,1929,Amsterdam,1839.000000,PublisherNotKnown,De Aardbol. Magazijn van hedendaagsche land- e...,UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
14,2836,Savona,1897.000000,PublisherNotKnown,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...
15,2854,London,1865.000000,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
16,2956,Paris,1860.000000,PublisherNotKnown,"Géodésie d'une partie de la Haute Éthiopie,...","ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
17,2957,Paris,1873.000000,PublisherNotKnown,[With eleven maps.],"ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
18,3017,Puerto-Rico,1866.000000,PublisherNotKnown,"[Historia geográfica, civil y politica de la ...","ABBAD Y LASIERRA, Agustín Íñigo - Bishop of...",http://www.flickr.com/photos/britishlibrary/ta...
19,3131,New York,1899.000000,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.",http://www.flickr.com/photos/britishlibrary/ta...
20,4598,Hull,1814.000000,The Author,Peace: a lyric poem. [With prefatory address b...,"ABBOTT, Thomas Eastoe.",http://www.flickr.com/photos/britishlibrary/ta...
21,4884,London,1820.000000,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
22,4976,Oxonii,1800.000000,"J. Cooke, etc.",[Abdollatiphi Historiæ Ægypti compendium. [Wit...,UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
23,5382,London,1847.000000,Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
24,5385,London,1897.000000,"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
25,5389,London,1897.000000,"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
26,5432,Milano,1893.000000,PublisherNotKnown,Signa: opera in tre atti [founded on the novel...,"A'BECKETT, Gilbert Arthur - and RUDALL (H. A.)",http://www.flickr.com/photos/britishlibrary/ta...
27,6036,London,1805.000000,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
28,6821,Aberdeen,1837.000000,J. Davidson & Co.,Description of the Coast between Aberdeen and ...,UnknownAuthor,http://www.flickr.com/photos/britishlibrary/ta...
29,7521,Wien,1896.000000,PublisherNotKnown,Aus Kaukasischen Ländern. Reisebriefe von H. ...,"ABICH, Wilhelm Hermann.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
data['date of publication'] = data['date of publication'].astype(str).str.replace('.0', '', regex=False)
data.head(2)

,identifier,place of publication,date of publication,publisher,title,author,flickr url
0,206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
# check duplicates
data.duplicated().sum()

np.int64(0)

In [ ]:
data = data.drop_duplicates()

In [ ]:
# final check
data.info()
data.isnull().sum()
data.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   identifier            8287 non-null   int64
 1   place of publication  8287 non-null   object
 2   date of publication   8287 non-null   object
 3   publisher             8287 non-null   object
 4   title                 8287 non-null   object
 5   author                8287 non-null   object
 6   flickr url            8287 non-null   object
dtypes: int64(1), object(6)
memory usage: 453.3+ KB

,identifier,place of publication,date of publication,publisher,title,author,flickr url
0,206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...